# Generated by Django 2.2.28 on 2022-07-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_seeker',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_specialist',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
