# Generated by Django 2.2.28 on 2022-07-02 11:59

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220702_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to=utils.generate_file_name),
        ),
        migrations.AddField(
            model_name='profile',
            name='modality',
            field=models.CharField(blank=True, choices=[('Astrology', 'Astrology'), ('Breathwork', 'Breathwork'), ('Energy_Medicine', 'Energy medicine (reiki)'), ('Life_Coaching', 'Life coaching'), ('Meditation', 'Meditation'), ('Nutrition', 'Nutrition'), ('Personal_Training', 'Personal training'), ('Sound_Healing', 'Sound healing'), ('Tarot', 'Tarot'), ('Yoga', 'Yoga')], default='Astrology', max_length=50, null=True),
        ),
    ]
