# Generated by Django 3.2 on 2022-09-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deposit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
